api_platform:
    title: Tracktik Integration API Platform
    version: 1.0.0
    # Mercure integration, remove if unwanted
    mercure:
        include_type: true
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    # Configure supported formats
    formats:
        json:     ['application/json']
        jsonld:   ['application/ld+json']
    # Patch format configuration
    patch_formats:
        json:
            mime_types: ['application/merge-patch+json']
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/Dto'
    swagger:
        versions: [3]
