# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Controllers
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
        autowire: true

    App\Service\TokenEncryptor:
        arguments:
            $encryptionKey: '%env(OAUTH_ENCRYPTION_KEY)%'

    # Add serializer normalizers
    serializer.normalizer.object:
        class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
        arguments:
            - '@serializer.mapping.class_metadata_factory'
            - null
            - '@property_accessor'
            - '@property_info'
        tags: [serializer.normalizer]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
